/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora2;


public class TelaCalculadora extends javax.swing.JFrame {

    double num1 = 0, num2 = 0, resultado = 0, numDigitado;
    String operacao = "";     

    public TelaCalculadora() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        tela = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoMais = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botaoDiv = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botaoMult = new javax.swing.JButton();
        botaoMenos = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botaoPonto = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        botaoApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.cyan, null, java.awt.Color.blue));
        jPanel1.setToolTipText("Calculator");
        jPanel1.setName(""); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Calculadora");
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        tela.setFont(new java.awt.Font("Dubai Light", 1, 22)); // NOI18N
        tela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        tela.setFocusable(true);

        botaoLimpar.setBackground(new java.awt.Color(204, 255, 255));
        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoLimpar.setText("Limpar Tela");
        botaoLimpar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparMouseClicked(evt);
            }
        });

        botaoMais.setBackground(new java.awt.Color(102, 255, 255));
        botaoMais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoMais.setText("+");
        botaoMais.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMaisMouseClicked(evt);
            }
        });

        botao7.setBackground(new java.awt.Color(102, 255, 255));
        botao7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao7.setText("7");
        botao7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao7MouseClicked(evt);
            }
        });
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });
        botao7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao7KeyPressed(evt);
            }
        });

        botao8.setBackground(new java.awt.Color(102, 255, 255));
        botao8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao8.setText("8");
        botao8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao8MouseClicked(evt);
            }
        });
        botao8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao8KeyPressed(evt);
            }
        });

        botao9.setBackground(new java.awt.Color(102, 255, 255));
        botao9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao9.setText("9");
        botao9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao9MouseClicked(evt);
            }
        });

        botaoDiv.setBackground(new java.awt.Color(102, 255, 255));
        botaoDiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoDiv.setText("/");
        botaoDiv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDivMouseClicked(evt);
            }
        });

        botao4.setBackground(new java.awt.Color(102, 255, 255));
        botao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao4.setText("4");
        botao4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao4MouseClicked(evt);
            }
        });

        botao5.setBackground(new java.awt.Color(102, 255, 255));
        botao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao5.setText("5");
        botao5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao5MouseClicked(evt);
            }
        });

        botao6.setBackground(new java.awt.Color(102, 255, 255));
        botao6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao6.setText("6");
        botao6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao6MouseClicked(evt);
            }
        });

        botaoMult.setBackground(new java.awt.Color(102, 255, 255));
        botaoMult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoMult.setText("*");
        botaoMult.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMultMouseClicked(evt);
            }
        });

        botaoMenos.setBackground(new java.awt.Color(102, 255, 255));
        botaoMenos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoMenos.setText("-");
        botaoMenos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMenosMouseClicked(evt);
            }
        });

        botao3.setBackground(new java.awt.Color(102, 255, 255));
        botao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao3.setText("3");
        botao3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao3MouseClicked(evt);
            }
        });

        botaoIgual.setBackground(new java.awt.Color(102, 255, 255));
        botaoIgual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoIgual.setText("=");
        botaoIgual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIgualMouseClicked(evt);
            }
        });

        botao0.setBackground(new java.awt.Color(102, 255, 255));
        botao0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao0.setText("0");
        botao0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao0MouseClicked(evt);
            }
        });

        botao2.setBackground(new java.awt.Color(102, 255, 255));
        botao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao2.setText("2");
        botao2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2MouseClicked(evt);
            }
        });

        botao1.setBackground(new java.awt.Color(102, 255, 255));
        botao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao1.setText("1");
        botao1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1MouseClicked(evt);
            }
        });

        botaoPonto.setBackground(new java.awt.Color(102, 255, 255));
        botaoPonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoPonto.setText(".");
        botaoPonto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPontoMouseClicked(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Designed by Dener");
        jTextField2.setBorder(null);

        botaoApagar.setBackground(new java.awt.Color(204, 255, 255));
        botaoApagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoApagar.setText("C");
        botaoApagar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoApagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botaoPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoDiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMenos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao7KeyPressed
        if (evt.getKeyCode() == evt.VK_7) {
            tela.setText(tela.getText() + "7");
        }
    }//GEN-LAST:event_botao7KeyPressed

    private void botao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao7MouseClicked
        tela.setText(tela.getText() + "7");
    }//GEN-LAST:event_botao7MouseClicked

    private void botao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao8MouseClicked
        tela.setText(tela.getText() + "8");
    }//GEN-LAST:event_botao8MouseClicked

    private void botao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao9MouseClicked
        tela.setText(tela.getText() + "9");
    }//GEN-LAST:event_botao9MouseClicked

    private void botao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao4MouseClicked
        tela.setText(tela.getText() + "4");
    }//GEN-LAST:event_botao4MouseClicked

    private void botao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao5MouseClicked
        tela.setText(tela.getText() + "5");
    }//GEN-LAST:event_botao5MouseClicked

    private void botao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao6MouseClicked
        tela.setText(tela.getText() + "6");
    }//GEN-LAST:event_botao6MouseClicked

    private void botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseClicked
        tela.setText(tela.getText() + "1");
    }//GEN-LAST:event_botao1MouseClicked

    private void botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseClicked
        tela.setText(tela.getText() + "2");
    }//GEN-LAST:event_botao2MouseClicked

    private void botao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao3MouseClicked
        tela.setText(tela.getText() + "3");
    }//GEN-LAST:event_botao3MouseClicked

    private void botao0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao0MouseClicked
        tela.setText(tela.getText() + "0");
    }//GEN-LAST:event_botao0MouseClicked

    private void botaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparMouseClicked
        tela.setText("");
        num1 = 0;
        num2 = 0;
        resultado = 0;
        operacao = "";
    }//GEN-LAST:event_botaoLimparMouseClicked

    private void botaoDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDivMouseClicked
     num1 = Double.parseDouble(tela.getText());
     tela.setText("");
     operacao = "/";
    }//GEN-LAST:event_botaoDivMouseClicked

    private void botaoMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMultMouseClicked
    num1 = Double.parseDouble(tela.getText());
    tela.setText("");
    operacao = "*";
    }//GEN-LAST:event_botaoMultMouseClicked

    private void botaoMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenosMouseClicked
    num1 = Double.parseDouble(tela.getText());
    tela.setText("");
    operacao = "-";
    }//GEN-LAST:event_botaoMenosMouseClicked

    private void botaoMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMaisMouseClicked
    num1 = Double.parseDouble(tela.getText());
    tela.setText("");
    operacao = "+";
    }//GEN-LAST:event_botaoMaisMouseClicked

    private void botaoIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIgualMouseClicked
        num2 = Double.parseDouble(tela.getText());
        
        switch (operacao){
        case "/":
            resultado = num1 / num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "*":
            resultado = num1 * num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "-":
            resultado = num1 - num2;
            tela.setText(String.valueOf(resultado));
            break;          
            case "+":
            resultado = num1 + num2;
            tela.setText(String.valueOf(resultado));
            break;
    }
    }//GEN-LAST:event_botaoIgualMouseClicked

    private void botao8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao8KeyPressed
     if (evt.getKeyCode() == evt.VK_8) {
            tela.setText(tela.getText() + "8");
        }
    }//GEN-LAST:event_botao8KeyPressed

    private void botaoPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPontoMouseClicked
    tela.setText(tela.getText()+".");
    }//GEN-LAST:event_botaoPontoMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if((evt.getKeyCode() == evt.VK_1) || (evt.getKeyCode() == evt.VK_NUMPAD1)){
            tela.setText(tela.getText()+"1");
        }
        else if((evt.getKeyCode() == evt.VK_2) || (evt.getKeyCode() == evt.VK_NUMPAD2)){
            tela.setText(tela.getText()+"2");
        }
        else if((evt.getKeyCode() == evt.VK_3) || (evt.getKeyCode() == evt.VK_NUMPAD3)){
            tela.setText(tela.getText()+"3");
        }
        else if((evt.getKeyCode() == evt.VK_4) || (evt.getKeyCode() == evt.VK_NUMPAD4)){
            tela.setText(tela.getText()+"4");
        }
        else if((evt.getKeyCode() == evt.VK_5) || (evt.getKeyCode() == evt.VK_NUMPAD5)){
            tela.setText(tela.getText()+"5");
        }
        else if((evt.getKeyCode() == evt.VK_6) || (evt.getKeyCode() == evt.VK_NUMPAD6)){
            tela.setText(tela.getText()+"6");
        }
        else if((evt.getKeyCode() == evt.VK_7) || (evt.getKeyCode() == evt.VK_NUMPAD7)){
            tela.setText(tela.getText()+"7");
        }
        else if((evt.getKeyCode() == evt.VK_8) || (evt.getKeyCode() == evt.VK_NUMPAD8)){
            tela.setText(tela.getText()+"8");
        }
        else if((evt.getKeyCode() == evt.VK_9) || (evt.getKeyCode() == evt.VK_NUMPAD9)){
            tela.setText(tela.getText()+"9");
        }
        else if((evt.getKeyCode() == evt.VK_0) || (evt.getKeyCode() == evt.VK_NUMPAD0)){
            tela.setText(tela.getText()+"0");
        }
        else if (evt.getKeyCode() == evt.VK_DELETE){
            tela.setText("");
            num1 = 0;
            num2 = 0;
            resultado = 0;
            operacao = "";
        }
        else if (evt.getKeyCode() == evt.VK_BACK_SPACE){
            String str = tela.getText();
            StringBuilder w = new StringBuilder(str);
            str = String.valueOf(w.deleteCharAt(str.length()-1));
            tela.setText(str);
        }
        else if((evt.getKeyCode() == evt.VK_MINUS) || (evt.getKeyCode() == evt.VK_SUBTRACT)){
        num1 = Double.parseDouble(tela.getText());
        tela.setText("");
        operacao = "-";
        }
        else if((evt.getKeyCode() == evt.VK_PLUS) || (evt.getKeyCode() == evt.VK_ADD)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "+";
        }
        else if((evt.getKeyCode() == evt.VK_SLASH) || (evt.getKeyCode() == evt.VK_DIVIDE)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "/";
        }
        else if((evt.getKeyCode() == evt.VK_ASTERISK) || (evt.getKeyCode() == evt.VK_MULTIPLY)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "*";
        }
        else if((evt.getKeyCode() == evt.VK_PERIOD) || (evt.getKeyCode() == evt.VK_DECIMAL)){
         tela.setText(tela.getText()+".");
        }
        else if(evt.getKeyCode() == evt.VK_ENTER){
         num2 = Double.parseDouble(tela.getText());
        
        switch (operacao){
        case "/":
            resultado = num1 / num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "*":
            resultado = num1 * num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "-":
            resultado = num1 - num2;
            tela.setText(String.valueOf(resultado));
            break;          
            case "+":
            resultado = num1 + num2;
            tela.setText(String.valueOf(resultado));
            break;
        }
    }//GEN-LAST:event_jTextField1KeyPressed
    }
    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
         if((evt.getKeyCode() == evt.VK_1) || (evt.getKeyCode() == evt.VK_NUMPAD1)){
            tela.setText(tela.getText()+"1");
        }
        else if((evt.getKeyCode() == evt.VK_2) || (evt.getKeyCode() == evt.VK_NUMPAD2)){
            tela.setText(tela.getText()+"2");
        }
        else if((evt.getKeyCode() == evt.VK_3) || (evt.getKeyCode() == evt.VK_NUMPAD3)){
            tela.setText(tela.getText()+"3");
        }
        else if((evt.getKeyCode() == evt.VK_4) || (evt.getKeyCode() == evt.VK_NUMPAD4)){
            tela.setText(tela.getText()+"4");
        }
        else if((evt.getKeyCode() == evt.VK_5) || (evt.getKeyCode() == evt.VK_NUMPAD5)){
            tela.setText(tela.getText()+"5");
        }
        else if((evt.getKeyCode() == evt.VK_6) || (evt.getKeyCode() == evt.VK_NUMPAD6)){
            tela.setText(tela.getText()+"6");
        }
        else if((evt.getKeyCode() == evt.VK_7) || (evt.getKeyCode() == evt.VK_NUMPAD7)){
            tela.setText(tela.getText()+"7");
        }
        else if((evt.getKeyCode() == evt.VK_8) || (evt.getKeyCode() == evt.VK_NUMPAD8)){
            tela.setText(tela.getText()+"8");
        }
        else if((evt.getKeyCode() == evt.VK_9) || (evt.getKeyCode() == evt.VK_NUMPAD9)){
            tela.setText(tela.getText()+"9");
        }
        else if((evt.getKeyCode() == evt.VK_0) || (evt.getKeyCode() == evt.VK_NUMPAD0)){
            tela.setText(tela.getText()+"0");
        }
        else if (evt.getKeyCode() == evt.VK_BACK_SPACE){
            String str = tela.getText();
            StringBuilder w = new StringBuilder(str);
            str = String.valueOf(w.deleteCharAt(str.length()-1));
            tela.setText(str);
        }
        else if (evt.getKeyCode() == evt.VK_DELETE){
            tela.setText("");
            num1 = 0;
            num2 = 0;
            resultado = 0;
            operacao = "";
        }
        else if((evt.getKeyCode() == evt.VK_MINUS) || (evt.getKeyCode() == evt.VK_SUBTRACT)){
        num1 = Double.parseDouble(tela.getText());
        tela.setText("");
        operacao = "-";
        }
        else if((evt.getKeyCode() == evt.VK_PLUS) || (evt.getKeyCode() == evt.VK_ADD)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "+";
        }
        else if((evt.getKeyCode() == evt.VK_SLASH) || (evt.getKeyCode() == evt.VK_DIVIDE)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "/";
        }
        else if((evt.getKeyCode() == evt.VK_ASTERISK) || (evt.getKeyCode() == evt.VK_MULTIPLY)){
         num1 = Double.parseDouble(tela.getText());
         tela.setText("");
         operacao = "*";
        }
        else if((evt.getKeyCode() == evt.VK_PERIOD) || (evt.getKeyCode() == evt.VK_DECIMAL)){
         tela.setText(tela.getText()+".");
        }
        else if(evt.getKeyCode() == evt.VK_ENTER){
         num2 = Double.parseDouble(tela.getText());
        
        switch (operacao){
        case "/":
            resultado = num1 / num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "*":
            resultado = num1 * num2;
            tela.setText(String.valueOf(resultado));
            break;
            case "-":
            resultado = num1 - num2;
            tela.setText(String.valueOf(resultado));
            break;          
            case "+":
            resultado = num1 + num2;
            tela.setText(String.valueOf(resultado));
            break;
        }
    }                                      
    }//GEN-LAST:event_jPanel1KeyPressed

    private void botaoApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoApagarMouseClicked
        String str = tela.getText();
        StringBuilder w = new StringBuilder(str);
        str = String.valueOf(w.deleteCharAt(str.length()-1));
        tela.setText(str);
    }//GEN-LAST:event_botaoApagarMouseClicked
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoDiv;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoMais;
    private javax.swing.JButton botaoMenos;
    private javax.swing.JButton botaoMult;
    private javax.swing.JButton botaoPonto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel tela;
    // End of variables declaration//GEN-END:variables
}
